ajax/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView
from core import views as views_core


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^books/$', views_core.book_list, name='book_list'),
    url(r'^books/create/$', views_core.book_create, name='book_create'),
    url(r'^books/update/(?P<pk>\d+)/$',
        views_core.book_update, name='book_update'),
    url(r'^books/delete/(?P<pk>\d+)/$',
        views_core.book_delete, name='book_delete'),
    url(r'^admin/', admin.site.urls),
]

core/models.py
from django.db import models
from django.shortcuts import resolve_url as r


class Books(models.Model):
    HARDCOVER = 1
    PAPERBACK = 2
    EBOOK = 3
    BOOK_TYPES = (
        (HARDCOVER, 'Hardcover'),
        (PAPERBACK, 'Paperback'),
        (EBOOK, 'E-book'),
    )

    title = models.CharField(max_length=50)
    author = models.CharField(max_length=30)
    publication_date = models.DateField(null=True)
    pages = models.IntegerField(blank=True, null=True)
    price = models.DecimalField(decimal_places=2, max_digits=5)
    book_type = models.PositiveSmallIntegerField(choices=BOOK_TYPES)

    class Meta:
        ordering = ('title',)
        verbose_name = 'livro'
        verbose_name_plural = 'livros'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return r('book_update', pk=self.pk)

core/forms.py
from django import forms
from .models import Books


class BookForms(forms.ModelForm):

    class Meta:
        model = Books
        fields = ('title', 'author', 'publication_date',
                  'pages', 'price', 'book_type',)

core/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from core.models import Books
from core.forms import BookForms


def book_list(request):
    books = Books.objects.all()
    return render(request, 'book_list.html', {'book_list': books})


def book_create_form(request, form, template_name):
    data = {}
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            books = Books.objects.all()
            data['html_book_list'] = render_to_string(
                'includes/partial_book_list.html', {'book_list': books})
            data['is_form_valid'] = True
        else:
            data['is_form_valid'] = False

    context = {'form': form}
    data['html_form'] = render_to_string(
        template_name, context, request=request)

    return JsonResponse(data)


def book_create(request):
    if request.method == 'POST':
        form = BookForms(request.POST)
    else:
        form = BookForms()

    return book_create_form(request, form, 'includes/partial_book_create.html')


def book_update(request, pk):
    book = get_object_or_404(Books, pk=pk)

    if request.method == 'POST':
        form = BookForms(request.POST, instance=book)
    else:
        form = BookForms(instance=book)

    return book_create_form(request, form, 'includes/partial_book_update.html')


def book_delete(request, pk):
    data = {}
    book = get_object_or_404(Books, pk=pk)

    if request.method == 'POST':
        book.delete()
        books = Books.objects.all()
        data['is_form_valid'] = True
        data['html_book_list'] = render_to_string(
            'includes/partial_book_list.html', {'book_list': books})
    else:
        data['is_form_valid'] = False
        context = {'book': book}
        data['html_form'] = render_to_string(
            'includes/partial_book_delete.html', context, request=request)

    return JsonResponse(data)

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Simple Ajax</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    {% include 'includes/header.html' %}


    <div class="container">
        {% block content %}


        {% endblock %}
    </div>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>-->
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/apps.js' %}"></script>
  </body>
</html>

core/templates/book_list.html
{% extends 'base.html'%}

{% block content %}

<h1 class="page-header"> Books </h1>

<!-- button triger function -->
<p>
    <button type="button" class="btn btn-primary js-create-book" data-url="{% url 'book_create' %}" >
        <span class="glyphicon glyphicon-plus "></span>
        New Book
    </button>
</p>

<!-- table -->
<table class="table table-striped" id="book-table">
    <thead>
        <tr>
            <td>#</td>
            <td>Title</td>
            <td>Author</td>
            <td>Type</td>
            <td>Publication date</td>
            <td>Page</td>
            <td>Price</td>

        </tr>
    </thead>

    <tbody>

        {% include 'includes/partial_book_list.html' %}

    </tbody>


</table>


<!-- modal -->
<div class="modal fade" id="modal-book">
    <div class="modal-dialog">
        <div class="modal-content">


        </div>
    </div>
</div>
{% endblock %}

core/templates/includes/header.html
 <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

            <a class="navbar-brand" href="#">AJAX</a>

        </div>
        <div id="navbar" class="navbar-collapse collapse">



            <ul class="nav navbar-nav">

                <li class="active"><a href="{% url 'home' %}">Home</a></li>

                <li><a href="{% url 'book_list' %}">Books</a></li>
                <!-- <li><a href="#contact">Contact</a></li> -->

              <!--<li class="dropdown">-->

                  <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"-->
                    <!--aria-expanded="false">Dropdown <span class="caret"></span></a>-->
                <!--<ul class="dropdown-menu">-->
                    <!--<li><a href="#">Action</a></li>-->
                    <!--<li><a href="#">Another action</a></li>-->
                    <!--<li><a href="#">Something else here</a></li>-->
                    <!--<li role="separator" class="divider"></li>-->
                    <!--<li class="dropdown-header">Nav header</li>-->
                    <!--<li><a href="#">Separated link</a></li>-->
                    <!--<li><a href="#">One more separated link</a></li>-->

                <!--</ul>-->

              <!--</li>-->
                </ul>
                <!--<ul class="nav navbar-nav navbar-right">-->
                    <!--<li><a href="../navbar/">Default</a></li>-->
                    <!--<li class="active"><a href="./">Static top <span class="sr-only">(current)</span></a></li>-->
                    <!--<li><a href="../navbar-fixed-top/">Fixed top</a></li>-->
                <!--</ul>-->
        </div><!--/.nav-collapse -->
      </div>
    </nav>

core/templates/includes/partial_book_create.html
{% load widget_tweaks %}
<form action="{% url 'book_create' %}" method="POST" class="js-book-create-form">

    {% csrf_token %}

    <div class="modal-header">
        <button class="close" aria-label="Close" data-dismiss="modal" type="button">
            <span aria-hidden="True">&times;</span>
        </button>

        <h4 class="modal-title"> Create New book </h4>

    </div> <!-- header -->

    <div class="modal-body">

        {% include 'includes/partial_book_form.html' %}

    </div><!-- body -->

    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" > Create Book </button>
    </div><!-- footer -->
</form>

core/templates/includes/partial_book_delete.html
<form action="{% url 'book_delete' book.id %}" method="POST" class="js-book-delete-form">

    {% csrf_token %}

    <div class="modal-header">
        <button class="close" aria-label="Close" data-dismiss="modal" type="button">
            <span aria-hidden="True">&times;</span>
        </button>

        <h4 class="modal-title"> Delete book  </h4>

    </div> <!-- header -->

    <div class="modal-body">

        <p class=""> Você tem certeza que deseja deletar esse Livro? </p>
        <p><strong class="lead"> ID: {{ book.id }}</strong></p>
        <p><strong class="lead"> Titulo: {{ book.title }}</strong></p>
        <p><strong class="lead"> Autor: {{ book.author }}</strong></p>

    </div><!-- body -->

    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-danger" >Delete Book</button>
    </div><!-- footer -->
</form>

core/templates/includes/partial_book_form.html
{% load widget_tweaks %}

{% for field in form %}
<div class="form-group{% if field.errors %} has-error {% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
    <p class="help-block">{{ error }}</p>
    {% endfor %}
</div>
{% endfor %}

core/templates/includes/partial_book_list.html
{% for book in book_list %}
<tr>
    <td>{{ book.id }}</td>
    <td>{{ book.title }}</td>
    <td>{{ book.author }}</td>
    <td>{{ book.get_book_type_display }}</td>
    <td>{{ book.publication_date }}</td>
    <td>{{ book.pages }}</td>
    <td>{{ book.price }}</td>

    <td>
        <button class="btn btn-sm btn-warning js-book-update" type="button"
                data-url="{%  url 'book_update' book.id %}">
            <span class="glyphicon glyphicon-pencil"></span>
            Edit
        </button>
    </td>

    <td>
        <button class="btn btn-sm btn-danger js-book-delete" type="button"
                data-url="{%  url 'book_delete' book.id %}">
            <span class="glyphicon glyphicon-trash"></span>
            Delete
        </button>
    </td>
</tr>
{% empty %}
<tr>
    <td colspan="7" class="text-center bg-warning "> No Books</td>
</tr>
{% endfor %}

core/templates/includes/partial_book_update.html
<form action="{% url 'book_update' form.instance.pk %}" method="POST" class="js-book-update-form">

    {% csrf_token %}

    <div class="modal-header">
        <button class="close" aria-label="Close" data-dismiss="modal" type="button">
            <span aria-hidden="True">&times;</span>
        </button>

        <h4 class="modal-title"> Update book </h4>

    </div> <!-- header -->

    <div class="modal-body">

        {% include 'includes/partial_book_form.html' %}

    </div><!-- body -->

    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-warning" > Update Book </button>
    </div><!-- footer -->
</form>

core/templates/index.html
{% extends 'base.html'%}

{% block content %}

<div class="jumbotron">
  <h1> Ajax is coming </h1>
</div>


{% endblock %}